# Generated by Django 5.1.5 on 2025-02-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="deleted_at",
            new_name="updated_at",
        ),
        migrations.AlterField(
            model_name="blog",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
    ]
