# Generated by Django 5.1.5 on 2025-02-13 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="updated_at",
        ),
    ]
